version: '3.8'

services:
  app:
    container_name: nestjs_app
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3031:3031"
      - "9229:9229" # Debugging port
    environment:
      MONGODB_HOST: mongodb
      REDIS_HOST: redis
    command: sh -c "pnpm run start:start" # Start app with debugging
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules # Mount node_modules to avoid conflicts
    restart: always
